### ISSUE TITLE
Typo in Readme.md

### ISSUE THREAD

**Issue by craiglondon** [assayer-pro/yii2-cspreport#1]
There should not be a trailing semicolon outside of the double quote on the Apache config.

`Header set Content-Security-Policy-Report-Only "default-src https:; script-src https: 'unsafe-eval' 'unsafe-inline'; style-src https: 'unsafe-inline'; img-src https: data:; font-src https: data:; report-uri /csp-report";`

Should be inside the quote

`Header set Content-Security-Policy-Report-Only "default-src https:; script-src https: 'unsafe-eval' 'unsafe-inline'; style-src https: 'unsafe-inline'; img-src https: data:; font-src https: data:; report-uri /csp-report;"`

Additionally, from what I've been reading using unsafe-inline on script-src is not a best practice, kind of defeats the purpose.

**Comment by serge-larin** [comment]
Thanks. I don't use Apache and I wasn't possible to check this config. Fixed in commit 10cf288

> Additionally, from what I've been reading using unsafe-inline on script-src is not a best practice, kind of defeats the purpose.

This is example only, I had no purpose to create an absolutely secure configuration

**Comment by craiglondon** [comment]
Wow!  Thanks for the quick turn around!
